name: Build Pods

on:
  workflow_run:
    workflows: [Build RPMs]
    types:
    - completed

jobs:
  build_pods:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ManageIQ/manageiq-pods
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'manageiq-operator/go.mod'
    - name: Build pods containers
      run: |
        sudo apt-get remove docker
        bin/build -t latest -n
